"""
Pre-specified architectures
"""
from gpflux.architectures.constant_input_dim_deep_gp import  build_constant_input_dim_deep_gp
from gpflux.architectures.constant_input_dim_orthogonal_deep_gp import build_constant_input_dim_orth_deep_gp
from gpflux.architectures.constant_input_dim_het_orthogonal_deep_gp import  build_constant_input_dim_het_orth_deep_gp